<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>marko</string>
	</array>
	<key>name</key>
	<string>Marko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(style)\s+(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CSS style block, eg: style { color: green }</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(style)\.(less)\s+(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.marko.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Less style block, eg: style.less { color: green }</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.less</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(style)\.(scss)\s+(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.marko.css</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.marko.css</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko.css</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SCSS style block, eg: style.scss { color: green }</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko.css</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?:(static )|(?=(?:class|import|export) ))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.static.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Top level blocks parsed as JavaScript</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>(?=\n|$)</string>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-statement</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#content-concise-mode</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?:\s+|,)(?:(key|on[a-zA-Z0-9_$-]+|[a-zA-Z0-9_$]+Change|no-update(?:-body)?(?:-if)?)|([a-zA-Z0-9_$][a-zA-Z0-9_$-]*))(:[a-zA-Z0-9_$][a-zA-Z0-9_$-]*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.attribute-name.marko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.marko</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.function.attribute-name.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Attribute with optional value</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>name</key>
					<string>meta.marko-attribute</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-args-or-method</string>
						</dict>
						<dict>
							<key>applyEndPatternLast</key>
							<integer>1</integer>
							<key>begin</key>
							<string>\s*(:?=)\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>source.js</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attribute value</string>
							<key>contentName</key>
							<string>source.js</string>
							<key>end</key>
							<string>(?=.|$)</string>
							<key>name</key>
							<string>meta.embedded.js</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#javascript-expression</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(?:\s+|,)\.\.\.</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.spread.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>A ...spread attribute</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>name</key>
					<string>meta.marko-spread-attribute</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(,(?!,))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>comment</key>
					<string>Consume any whitespace after a comma</string>
					<key>end</key>
					<string>(?!\S)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comment-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>concise-html-block</key>
		<dict>
			<key>begin</key>
			<string>\s*(--+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>--- HTML block within concise mode content. ---</string>
			<key>end</key>
			<string>\1</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.marko-html-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-html-mode</string>
				</dict>
			</array>
		</dict>
		<key>concise-html-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tag-html</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#placeholder</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.+?</string>
							<key>name</key>
							<string>string</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>-- HTML line within concise mode content. (content-html-mode w/o scriptlet)</string>
			<key>match</key>
			<string>\s*(--+)(?=\s+\S)(.*$)</string>
			<key>name</key>
			<string>meta.section.marko-html-line</string>
		</dict>
		<key>concise-open-tag-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-before-attrs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.marko</string>
						</dict>
					</dict>
					<key>end</key>
					<string>]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!^)(?= )</string>
					<key>end</key>
					<string>(?=--)|(?&lt;!,)(?=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>concise-script-block</key>
		<dict>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>--- Embedded concise script content block. ---</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.marko-script-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-script</string>
				</dict>
			</array>
		</dict>
		<key>concise-script-line</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>-- Embedded concise script content line.</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.section.marko-script-line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-script</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-block</key>
		<dict>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>--- Embedded concise style content block. ---</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-block-less</key>
		<dict>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>--- Embedded concise style content block. ---</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-less</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-block-scss</key>
		<dict>
			<key>begin</key>
			<string>(\s+)(--+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>--- Embedded concise style content block. ---</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>end</key>
			<string>(\2)|(?=^(?!\1)\s*\S)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.end.marko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.section.marko-style-block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-scss</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-line</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>-- Embedded concise style content line.</string>
			<key>contentName</key>
			<string>source.css</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-line-less</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>-- Embedded concise style content line.</string>
			<key>contentName</key>
			<string>source.less</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-less</string>
				</dict>
			</array>
		</dict>
		<key>concise-style-line-scss</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\s*(--+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.begin.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>-- Embedded concise style content line.</string>
			<key>contentName</key>
			<string>source.scss</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.section.marko-style-line</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#content-embedded-style-scss</string>
				</dict>
			</array>
		</dict>
		<key>content-concise-mode</key>
		<dict>
			<key>comment</key>
			<string>Concise mode content block.</string>
			<key>name</key>
			<string>meta.marko-concise-content</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scriptlet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#concise-html-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#concise-html-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-html</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>A concise html tag.</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\.less\b)</string>
							<key>comment</key>
							<string>Concise style tag less</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block-less</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line-less</string>
								</dict>
							</array>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\.scss\b)</string>
							<key>comment</key>
							<string>Concise style tag scss</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block-scss</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line-scss</string>
								</dict>
							</array>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=style\b)</string>
							<key>comment</key>
							<string>Concise style tag</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-block</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-style-line</string>
								</dict>
							</array>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=script\b)</string>
							<key>comment</key>
							<string>Concise script tag</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-script-block</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#concise-script-line</string>
								</dict>
							</array>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(\s*)(?=[a-zA-Z0-9_$@])</string>
							<key>comment</key>
							<string>Normal concise tag</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#concise-open-tag-content</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#content-concise-mode</string>
								</dict>
							</array>
							<key>while</key>
							<string>(?=^\1\s+(\S|$))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-script</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style-less</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css.less</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
		</dict>
		<key>content-embedded-style-scss</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.css.scss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
		</dict>
		<key>content-html-mode</key>
		<dict>
			<key>comment</key>
			<string>HTML mode content block.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scriptlet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#placeholder</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.+?</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>html-args-or-method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-args</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\))\s*(?=\{)</string>
					<key>comment</key>
					<string>Attribute method shorthand following parens</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(?&lt;=\})</string>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>html-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;!(--)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML comments, doctypes &amp; cdata</string>
					<key>end</key>
					<string>\2&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.marko</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;html-comment&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Preserved HTML comment tag</string>
					<key>end</key>
					<string>&lt;/html-comment&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.marko</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.marko</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>[^\s]</string>
			<key>name</key>
			<string>invalid.illegal.character-not-allowed-here.marko</string>
		</dict>
		<key>javascript-args</key>
		<dict>
			<key>begin</key>
			<string>(?=\()</string>
			<key>comment</key>
			<string>Javascript style arguments</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>javascript-comment-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>JavaScript // single line comment</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>match</key>
			<string>\s*//.*$</string>
		</dict>
		<key>javascript-comment-multiline</key>
		<dict>
			<key>begin</key>
			<string>\s*(?=/\*)</string>
			<key>comment</key>
			<string>JavaScript /* block comment */</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>(?&lt;=\*/)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>javascript-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-comment-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-comment-line</string>
				</dict>
			</array>
		</dict>
		<key>javascript-enclosed</key>
		<dict>
			<key>comment</key>
			<string>Matches JavaScript content and ensures enclosed blocks are matched.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#javascript-args</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?={)</string>
					<key>end</key>
					<string>(?&lt;=})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=\[)</string>
					<key>end</key>
					<string>(?&lt;=])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=")</string>
					<key>end</key>
					<string>(?&lt;=")</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=')</string>
					<key>end</key>
					<string>(?&lt;=')</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=`)</string>
					<key>end</key>
					<string>(?&lt;=`)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/(?!&lt;[\]})A-Z0-9.&lt;%]\s*/)(?!/?&gt;|$)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.regexp.js</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>/[gimsuy]*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#regexp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)\s*(?:
								(?:\b(?:new|typeof|instanceof|in)\b)| # Keyword operators
								\&amp;\&amp;|\|\|| # Logical operators
								[\^|&amp;]| # Bitwise operators
								[!=]=|[!=]==|&lt;|&lt;[=&lt;]|=&gt;| # Comparison operators (Note you cannot use * or ? here)
								[?:]| # Ternary operators
								[-+*%](?!-) # Arithmetic operators
							)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\S)</string>
				</dict>
			</array>
		</dict>
		<key>javascript-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-enclosed</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>comment</key>
					<string>Match identifiers and member expressions</string>
					<key>match</key>
					<string>[0-9a-zA-Z$_.]+</string>
				</dict>
			</array>
		</dict>
		<key>javascript-statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-enclosed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>open-tag-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-before-attrs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?= )</string>
					<key>comment</key>
					<string>Attributes begin after the first space within the tag name</string>
					<key>end</key>
					<string>(?=/?&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attrs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>placeholder</key>
		<dict>
			<key>begin</key>
			<string>\$!?{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.template-expression.begin.js</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>${ } placeholder</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.template-expression.end.js</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>scriptlet</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\$)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.scriptlet.marko</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>An inline JavaScript scriptlet.</string>
			<key>contentName</key>
			<string>source.js</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.embedded.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javascript-statement</string>
				</dict>
			</array>
		</dict>
		<key>tag-before-attrs</key>
		<dict>
			<key>comment</key>
			<string>Everything in a tag before the attributes content</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-name</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Shorthand class or ID attribute</string>
					<key>match</key>
					<string>[#.][a-zA-Z0-9_$][a-zA-Z0-9_$-]*</string>
					<key>name</key>
					<string>entity.other.attribute-name.marko</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/(?!/)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Variable for a tag</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(?=:?\=|\s|&gt;|$|\||\(|/)</string>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>Match identifiers</string>
							<key>match</key>
							<string>[a-zA-Z$_][0-9a-zA-Z$_]*</string>
							<key>name</key>
							<string>variable.other.constant.object.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#object-binding-pattern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#array-binding-pattern</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js#var-single-variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>\s*(:?=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>comment</key>
					<string>Default attribute value</string>
					<key>contentName</key>
					<string>source.js</string>
					<key>end</key>
					<string>(?=.|$)</string>
					<key>name</key>
					<string>meta.embedded.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#javascript-expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Parameters for a tag</string>
					<key>end</key>
					<string>\|</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js#function-parameters-body</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-args-or-method</string>
				</dict>
			</array>
		</dict>
		<key>tag-html</key>
		<dict>
			<key>comment</key>
			<string>Matches an HTML tag and its contents</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML void elements</string>
					<key>end</key>
					<string>/?&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\.less\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML style tag with less</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Style body content</string>
							<key>contentName</key>
							<string>source.less</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style-less</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\.scss\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML style tag with scss</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Style body content</string>
							<key>contentName</key>
							<string>source.less</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style-scss</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=style\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML style tag</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Style body content</string>
							<key>contentName</key>
							<string>source.css</string>
							<key>end</key>
							<string>\s*(&lt;/)(style)?(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-style</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=script\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML script tag</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Script body content</string>
							<key>contentName</key>
							<string>source.js</string>
							<key>end</key>
							<string>\s*(&lt;/)(script)?(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-embedded-script</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(&lt;)(?=[a-zA-Z0-9_$@])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.marko</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HTML normal tag</string>
					<key>end</key>
					<string>/&gt;|(?&lt;=\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.marko</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#open-tag-content</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>&gt;</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Body content</string>
							<key>end</key>
							<string>\s*(&lt;/)([a-zA-Z0-9_$:@-]+)?(.*?)(&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
								<key>2</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#tag-name</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#invalid</string>
										</dict>
									</array>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.end.marko</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#content-html-mode</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\${</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.begin.js</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Dynamic tag.</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.end.js</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.marko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.marko.css</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>comment</key>
									<string>Core tag.</string>
									<key>match</key>
									<string>(attrs|return|import)(?=\b)</string>
									<key>name</key>
									<string>support.type.builtin.marko</string>
								</dict>
								<dict>
									<key>comment</key>
									<string>Core tag.</string>
									<key>match</key>
									<string>(for|if|while|else-if|else|macro|tag|await|let|const|effect|set|get|id|lifecycle)(?=\b)</string>
									<key>name</key>
									<string>support.function.marko</string>
								</dict>
								<dict>
									<key>comment</key>
									<string>Attribute tag.</string>
									<key>match</key>
									<string>@.+</string>
									<key>name</key>
									<string>entity.other.attribute-name.marko</string>
								</dict>
								<dict>
									<key>comment</key>
									<string>Native or userland tag.</string>
									<key>match</key>
									<string>.+</string>
									<key>name</key>
									<string>entity.name.tag.marko</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>match</key>
					<string>(style)\.([a-zA-Z0-9$_-]+(?:\.[a-zA-Z0-9$_-]+)*)|([a-zA-Z0-9_$@][a-zA-Z0-9_$@:-]*)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.marko</string>
	<key>uuid</key>
	<string>46c8c3f8-cabe-466a-a633-5deafdc51253</string>
</dict>
</plist>
